# Generated by Django 3.2.5 on 2021-09-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_productpictures_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpictures',
            name='picture',
            field=models.FileField(upload_to='product_pcitures/'),
        ),
    ]
