# Generated by Django 3.2.5 on 2021-09-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='use',
            new_name='user',
        ),
    ]
